### ISSUE TITLE
Looking for contributors?

### ISSUE THREAD

**Issue by sean-adams** [bitbybyte/quarter-zone#2]
Hey, I'm an avid TE:C player and software engineer, discovered Quarter Zone recently and it's great! Wondering if you're looking for any contributors / collaborators - I'm comfortable in JS, Python, and Ruby.

Sorry for creating this as an issue, it was the only way I could think of to get in contact.

**Comment by bitbybyte** [comment]
Hello! I really appreciate the offer and the sentiment. As it stands right now, the project is in a decently stable state. To give you some sense of the structure of this overall project:

- Scraper: C++ utilities that retrieve the leaderboards through their expected API routines
- Ingestion: Python to SQLite DB
- Page generation: Bash/Python scripts to static HTML
- Web server: nginx
- Discord bot: Python communicating with SQLite DB

This definitely has room to be optimized, especially on the scraper side due to some weird quirks with how it interacts with Steam.  Our main gap I would say right now is **retrieving single player data from missing platforms** like NSO, PSN, and Xbox. However, I would love to hear if you have ideas for making the project more presentable, exportable, etc. Some things I've been mulling over:

- Dark/light mode theming (and general cleanup of the CSS)
- API, exportable CSVs
- Present fun and interesting stats (platform representation, total SR, total matches observed, percent of users that have cleared Areas 1-5 -- there's a lot of interesting possibilities here)
- More dynamic pages -- what if you could compare SRs or other data directly? Show leaderboards from a past state/day?

If you have anything in mind, let me know. 🙂
